version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5432:5432"
  order-service:
    build: ./order
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    ports:
      - "8080:3000"
